name: Frontend CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run tests
        run: echo "Skipping tests for now"
        working-directory: ./frontend

      - name: Build
        run: npm run build
        working-directory: ./frontend

      # You can add deploy steps here (e.g., to Vercel, Netlify, S3)
